### ISSUE TITLE
phpCronMismatchDescription 翻译错误

### ISSUE THREAD

**Issue by wxiaoguang** [AS-php/WHMCS-zh-CN#1]
`$_ADMINLANG['healthCheck']['phpCronMismatchDescription'] = "您的环境似乎正在为System Cron运行与当前加载的PHP版本（<strong>：currentPhp </ strong>）不同的PHP版本（<strong>：cronPhp </ strong>）。 这可能会导致运行系统Cron的问题。";`

1、`：currentPhp` 和 `：cronPhp` 里面应该是英文分号

2、`</ strong>` 不应该有空格

**Comment by Rodots** [comment]
感谢您的反馈，已修正错误并更新v7.10.0版本的汉化补丁，欢迎关注
