### ISSUE TITLE
为啥设置后是英文

### ISSUE THREAD

**Issue by 904344156** [AS-php/WHMCS-zh-CN#11]
我将常规设置那里将默认语言改成Chinese-as，然后我尝试刷新页面居然是英文，我换成 Chinese就是简体中文

**Comment by Rodots** [comment]
> 我将常规设置那里将默认语言改成Chinese-as，然后我尝试刷新页面居然是英文，我换成 Chinese就是简体中文

那试试看留意一下，你在后台设置完默认语言后，回到首页刷新，你网站当前已选中的语言是简体中文(chinese-as)吗？

**Comment by 904344156** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
