### ISSUE TITLE
什么时候出繁体中文

### ISSUE THREAD

**Issue by rich168** [AS-php/WHMCS-zh-CN#5]
老大什么时候出繁体中文？
谢谢

**Comment by Rodots** [comment]
你好，官网已经自带繁体中文了呀，何必多此一举呢

**Comment by rich168** [comment]
怎么没看见啊

傲世 ***@***.***> 于 2022年2月19日周六 15:02写道：

**Comment by Rodots** [comment]
你好，官方自带的繁体中文包文件名是chinese.php，我们简体中文的文件名是chinese-as.php，你看看/admin/lang/目录和/lang目录就知道了
